### PR TITLE
Upgraded to NS 3.0

### LINKED ISSUE #4: Not ready for Nativescript 3
Hi PeterStaev,

Thank you very much for your plugin ;)
But I tried it with Nativescript 3 on my project, and I have the following error :

```bash
JS: TypeError: Could not load view for: ImageSwipe.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", relative to: app/tns_modules/
```

I think it's because 'ui/core/proxy' doesn't exist in Nativescript 3, but I don't know develop in native Nativescript, so may be it's not the problem.

Best Regards,
Marc

### PR DESCRIPTION
**Pull request by buuhuu**
Resolves #4

### CODE REVIEW

**Comment by buuhuu** [comment]
Tested that on demo-ng only

**Comment by PeterStaev** [comment]
Hey @Buuhuu , thanks for this work! Actually I've already started the conversion in the core3 branch. I've got android working but on iOS for some reason it does not work as expected. Have you tested your changes for iOS? Also on two places I see you divide the measured width by 3, can you explain this "magic number"? May be this is the device's pixel density?

**Comment by buuhuu** [comment]
Exactly. With the most recent commit i replaced that with screen.mainScreen.scale. This is working for both iOS and Android for me.

I had a look at your branch but as that was wip I decided to do it my self (bit under pressure with our timeline).

**Comment by PeterStaev** [comment]
Hey @Buuhuu , I've migrated your changes and merged the TNS 3.0 version to master. Big thanks for your help on resolving the iOS problems! The rest were more or less the same as what I had in the core3 branch 👍

**Comment by jlooper** [comment]
@buuhuu thanks for this great PR! Can I send a t-shirt your way as a token of our appreciation? You can DM me on Comm Slack

**Pull request closed without merging**
